# version: '3'

services:
  frontend:
    # build:
    #   context: .   # Directory containing the frontend Dockerfile and build context
    #   dockerfile: ./frontend/Dockerfile  # Specify the Dockerfile to use (optional if named "Dockerfile")
    image: ghcr.io/mariammbello/resume-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - mynetwork

  backend:
    # build:
    #   context: .     # Directory containing the backend Dockerfile and build context
    #   dockerfile: ./backend/Dockerfile  # Specify the Dockerfile to use (optional if named "Dockerfile")
    image: ghcr.io/mariammbello/resume-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/
      MONGO_DATABASE_NAME: resume_challenge
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - mynetwork
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Volume mount for MongoDB data persistence

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data:  # This defines the mongo-data volume