version: '3'

services:
  frontend:
    build:
      context: ./frontend    # Directory containing the frontend Dockerfile and build context
      dockerfile: Dockerfile  # Specify the Dockerfile to use (optional if named "Dockerfile")
    ports:
      - "80:80"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend     # Directory containing the backend Dockerfile and build context
      dockerfile: Dockerfile  # Specify the Dockerfile to use (optional if named "Dockerfile")
    ports:
      - "5000:5000"
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/
      MONGO_DATABASE_NAME: resume_challenge
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    networks:
      - mynetwork
    ports:
      - "27017:27017"

networks:
  mynetwork:
    driver: bridge
