name: Deploy_frontend

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.main.yml'

env:
  CONTAINER_IMAGE_NAME: mariammbello/resume-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v2

    - name: 'Login to GitHub Container Registry'
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: 'Build Docker image'
      run: |
        docker build -t ghcr.io/${{ env.CONTAINER_IMAGE_NAME }}:latest -f frontend/Dockerfile .

    - name: 'Push Docker image'
      run: |
        docker push ghcr.io/${{ env.CONTAINER_IMAGE_NAME }}:latest
